# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{nestful}
  s.version = "0.0.8"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Alex MacCaw}]
  s.date = %q{2012-01-05}
  s.description = %q{Simple Ruby HTTP/REST client with a sane API}
  s.email = %q{info@eribium.org}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "MIT-LICENSE",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "lib/nestful.rb",
    "lib/nestful/connection.rb",
    "lib/nestful/exceptions.rb",
    "lib/nestful/formats.rb",
    "lib/nestful/formats/blank_format.rb",
    "lib/nestful/formats/form_format.rb",
    "lib/nestful/formats/json_format.rb",
    "lib/nestful/formats/multipart_format.rb",
    "lib/nestful/formats/text_format.rb",
    "lib/nestful/formats/xml_format.rb",
    "lib/nestful/oauth.rb",
    "lib/nestful/request.rb",
    "lib/nestful/request/callbacks.rb",
    "lib/nestful/resource.rb",
    "nestful.gemspec"
  ]
  s.homepage = %q{http://github.com/maccman/nestful}
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.6}
  s.summary = %q{Simple Ruby HTTP/REST client with a sane API}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 2.3.12"])
    else
      s.add_dependency(%q<activesupport>, [">= 2.3.12"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 2.3.12"])
  end
end

